### PR TITLE
chore: add pull request form

### PR DESCRIPTION
**Pull request by tu6ge**
link: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Fixed tickets | #...

### CODE REVIEW

**Review by owenvoke — DISMISSED** [review]
This looks fine to me, up to you though @nunomaduro if you want it?

**Comment by tu6ge** [comment]
My English is weak. how should I change it?

**Comment by tu6ge** [comment]
Is the haved yaml Grammar error?

**Comment by owenvoke** [comment]
Sorry @tu6ge, I just noticed that it says:
> Issue forms are not supported for pull requests. You can create pull request templates in your repositories for collaborators to use. For more information, see "Creating a pull request template for your repository."

So, it looks like this isn't actually supported for the PR template. 😦

**Comment by tu6ge** [comment]
I got it. I'll change it later.

**Comment by nunomaduro** [comment]
cc @owenvoke

**Comment by nunomaduro** [comment]
No plans for this.

**Pull request closed without merging**
