### PR TITLE
[2.x] Adds support for chaining `hasNoExpectations` to the test method.

### PR DESCRIPTION
**Pull request by lukeraymonddowning**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes

A feature that is often useful in PHPUnit is `expectNotToPerformAssertions`. This is handy when you have a method that is simply testing that a method can be called without throwing any exceptions or causing any errors, without being interested in the end result.

This PR adds a new `hasNoExpectations` method to the `TestCall` class, which allows us to support this functionality in a style more aligned with Pest:

```php
it('does not throw any errors when run', function () {
    SomeComplexService::run();
})->hasNoExpectations();
```

By adding this, we provide 2 main benefits:

1) We allow for visual consistency with other Pest `TestCall` methods, such as `throws`
2) We use the term `expectations` instead of `assertions`, which Pest users are less familiar with

Kind Regards,
Luke

### CODE REVIEW

**Comment by freekmurze** [comment]
Very nice! You could opt to name `throwsNoExceptions` for even more visual consistency with `throws`.

**Comment by lukeraymonddowning** [comment]
@freekmurze I like that, but would it lead to devs mistakenly using it incorrectly? 

For example, a junior dev may put it on every test they expect to work. 

I may be wrong here, just my initial thoughts on it...

**Comment by freekmurze** [comment]
@lukeraymonddowning I think if `throwsNoExceptions` has good documentation, we can steer people away from abusing it.

Should it be decided that `hasNoExpectations` would be the way forward, I'll happily use it too 🙂

**Comment by JustSteveKing** [comment]
I think the term `hasNoExpectations` is a lot more descriptive to the action. This test has no expectations, it's clear the purpose of it whereas `throwsNoExceptions` while still clear could be confusing if read in a glance

**Comment by fabio-ivona** [comment]
+1 for `throwsNoExceptions`

**Pull request merged**
