### PR TITLE
feat(expectations): add toMatch

### PR DESCRIPTION
**Pull request by owenvoke**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Fixed tickets | #... 

I wasn't sure about the naming of this, whether it should be `toMatchRegEx`, `toMatchRegExp`, or `toMatchRegularExpression`. (The `toBe*` prefix doesn't really work with any of them).

### CODE REVIEW

**Comment by olivernybroe** [comment]
What if we just call it `toMatch` instead? 

Then let me do the following 
```php
expect('Hello World')->toMatch('/^hello wo.*$/i');
expect('Hello World')->toMatch('Hello World'); 
```

So a regex and a string is supported for matching.

**Comment by owenvoke** [comment]
@olivernybroe, that makes sense too. 👍🏻 Although, I wonder if people might get confused between `toBe` and `toMatch`. 🤔 @nunomaduro, what're your thoughts on this?

**Comment by olivernybroe** [comment]
@owenvoke Hmm true. Could we extend `toBe` to just support regex maybe?

**Comment by nunomaduro** [comment]
So, to give context. Normally, we mimic the API of Jest. In this case, Jest don't have this feature. So let's take a moment to actually make sure we don't make a mistake here.

JavaScript uses `match` : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match.


I think we can use `toMatchRegex` for now, and change it later if we think people will be confortable with an `toMatch`.

**Comment by olivernybroe** [comment]
@nunomaduro According to jest they use `toMatch` in their expect api
Which can take a string and a regex or am I misunderstanding something here? 👍 

https://jestjs.io/docs/en/expect#tomatchregexporstring

**Comment by nunomaduro** [comment]
@owenvoke @olivernybroe If Jest uses `toMatch`, let's use `toMatch` too. 👍

**Comment by owenvoke** [comment]
Pushed an update. 👍🏻

**Review by nunomaduro — APPROVED** [review]

**Comment by nunomaduro** [comment]
Fell free to merge, tag a new version, update the docs, and make a tweet about it @owenvoke .

**Comment by owenvoke** [comment]
@nunomaduro, I noticed you merged the docs for `toMatchConstraint`. Do you want me to merge #190 as well and include that in v0.3.6?

**Comment by nunomaduro** [comment]
@owenvoke Yes.

**Pull request merged**
