### PR TITLE
Matrix datasets

### PR DESCRIPTION
**Pull request by fabio-ivona**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Fixed tickets | -

**my aim is to allow a test to be written like this one:**

```php
it('uses a matrix of datasets', function($a, $b){
    expect($a * $b)->toBeNumeric();
})->with([1, 2, 3, 4])->with([5, 6, 7, 8]);


it('uses a matrix of datasets with variadic arguments', function($a, $b){
    expect($a * $b)->toBeNumeric();
})->with([1, 2, 3, 4], [5, 6, 7, 8]);
```

this will generate a matrix of combination of the two datasets (cartesian product) 

image

**this feature allows even more than two datasets:**

```php
it('uses 3D matrix of datasets', function($a, $b, $c){
    expect($a * $b * $c)->toBeNumeric();
})->with([1, 2, 3, 4])->with([5, 6])->with([7, 8]);

it('uses again a 3D matrix of datasets', function($a, $b, $c){
    expect($a * $b * $c)->toBeNumeric();
})->with([1, 2, 3, 4], [5, 6], [7, 8]);
```

and will output 

image

**obviously the original single-dataset management it is still supported**

```php
it('uses a simple datasets', function($a){
    expect($a)->toBeNumeric();
})->with([1, 2, 3, 4]);
```

image

**It supports named datasets**

```php
it('uses named datasets', function ($firstNumber, $secondNumber, $firstLetter, $secondLetter) {
    expect($firstNumber + $secondNumber . $firstLetter . $secondLetter)->toBeString();
})->with([
    'low numbers'  => [1, 2],
    'high numbers' => [50, 60],
])->with([
    'latin letters' => ['a', 'b'],
    'greek letters' => ['alpha', 'beta'],
]);
```

image

**as well as all other types of datasets (closures, shared, ecc. ecc.**

```php
it('uses shared datasets', function ($firstNumber, $secondNumber, $firstLetter, $secondLetter) {
    expect($firstNumber + $secondNumber . $firstLetter . $secondLetter)->toBeString();
})->with('numbers')->with('letters');
```

```php
it('uses lazy datasets', function ($firstNumber, $secondNumber, $letter) {
    expect($firstNumber + $secondNumber . $letter)->toBeString();
})->with(function(){
    yield [1, 2];
    yield [3, 4];
})->with(['a', 'b']);
```

### CODE REVIEW

**Comment by nunomaduro** [comment]
This sound promising - and a good feature. Be sure to add a good test suite for this.

**Comment by fabio-ivona** [comment]
Yep, I'm moving it to draft, in order to write more tests

Glad you like it!

**Comment by fabio-ivona** [comment]
@nunomaduro I added a new set of tests, trying to replicate all test cases that were written for single datasets (both unit and feature tests)

I also added a new way to add multiple datasets

now you can use the original syntax

```
it('uses shared datasets', function ($firstNumber, $secondNumber, $firstLetter, $secondLetter) {
    expect($firstNumber + $secondNumber . $firstLetter . $secondLetter)->toBeString();
})->with('numbers')->with('letters');
```

as well using multiple arguments in a single `with` :+1: 

```
it('uses shared datasets', function ($firstNumber, $secondNumber, $firstLetter, $secondLetter) {
    expect($firstNumber + $secondNumber . $firstLetter . $secondLetter)->toBeString();
})->with('numbers', 'letters');
```

what do you think?

**Comment by fabio-ivona** [comment]
@nunomaduro just refactored a bit and reviewed my code, I think it's ready for a deep review :smile:

**Comment by fabio-ivona** [comment]
@nunomaduro are there any issue with my implementation?

if you are just busy, please forgive me and ignore this message

**Comment by fabio-ivona** [comment]
@owenvoke there is a failing test, but it seems an error during the _Install Dependencies_ step is there any way to run it again?

**Comment by owenvoke** [comment]
@fabio-ivona, I've requested a re-run of that workflow and everything seems to be fine. 👍🏻

**Comment by fabio-ivona** [comment]
> @fabio-ivona, I've requested a re-run of that workflow and everything seems to be fine. 👍🏻

Thanks!

just to know, how can I speed up a review of this PR? is there any detail missing?

**Comment by fabio-ivona** [comment]
Update: merged code from master and updated test snapshots

**Comment by nunomaduro** [comment]
@fabio-ivona Can you update the documentation about this?

**Comment by fabio-ivona** [comment]
> @fabio-ivona Can you update the documentation about this?

Sure! I'm going to work on it this night

**Comment by fabio-ivona** [comment]
@nunomaduro done! pestphp/docs#56

I'm not a great non-code writer, please be merciful :smile:

**Pull request merged**
