### PR TITLE
feat(teamcity): Add basic teamcity output format

### PR DESCRIPTION
**Pull request by olivernybroe**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Fixed tickets | #140 

This pull request adds team city output support to pest.

A future pr could be added, so the exception stack trace uses collision format.

### CODE REVIEW

**Comment by nunomaduro** [comment]
Can you fix static analysis bugs buddy?

**Comment by olivernybroe** [comment]
This should be ready now 👍

**Comment by olivernybroe** [comment]
We probably could add some tests to check the output. However the biggest problem with the test is that we have to mimic the fake test case class we create 🙂

Might be worth it thougg as we prob. could use it for other tests also

**Comment by olivernybroe** [comment]
I have no idea how to fix this rector error tbh 👍

@owenvoke you know how?

**Comment by owenvoke** [comment]
Just investigating that issue, looks like it's due to the [`StaticCallOnNonStaticToInstanceCallRector`](https://github.com/rectorphp/rector/blob/1b059ee0c33df560233283cc95f24f47790317ca/rules/php70/src/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector.php) rector.

It's caused by [line 82 of the TeamCity class](https://github.com/pestphp/pest/blob/c67411c64c475e828efe6932ff610247c3fed687/src/TeamCity.php#L82).

**Comment by olivernybroe** [comment]
@owenvoke Sounds like an issue with `StaticCallOnNonStaticToInstanceCallRector` maybe? 

@TomasVotruba If you have a little time, could you help us on how to solve the rector error?

**Comment by TomasVotruba** [comment]
Just flying by... Could you report and issue on Rector? With input/output/expected output.

If it a blocker, check the @rectorphp README to exclude single rule

**Comment by olivernybroe** [comment]
@TomasVotruba Cool, I have created an issue https://github.com/rectorphp/rector/issues/3981 and will ignore the rule for now :)

**Comment by olivernybroe** [comment]
I would really like to get this out as part of next version. 

The phpstorm plugin has a bunch of issues which can't be resolved before this is added.

**Comment by owenvoke** [comment]
I thought this was already merged, I think it's fine. :+1:

**Comment by owenvoke** [comment]
Probably my bad for missing it. 😬 I've now merged it. 🎉

**Comment by olivernybroe** [comment]
Thanks!

**Pull request merged**
