### PR TITLE
[2.x] Track vendor changes

### PR DESCRIPTION
**Pull request by nuernbergerA**
we override some vendor file
to keep track of changes of those file we keep the hash to compare it later

i had to move two files to match the vendor file structure
* WarmCodeCoverageCacheCommand
* TestSkippedSubscriber

### CODE REVIEW

**Comment by nunomaduro** [comment]
This is crazy smart btw! Do you plan to finish this? Or should I do something?

**Comment by nuernbergerA** [comment]
@nunomaduro im handing this over to you.
the question is if you wanna run this test on every matrix-run or however you wanna be notified about changes

**Comment by nunomaduro** [comment]
> on every matrix-run 

This one.

**Comment by nuernbergerA** [comment]
@nunomaduro can you help here with the snapshot situation?

**Pull request merged**
