### PR TITLE
feat: adds support to PHPUnit 9.4

### PR DESCRIPTION
**Pull request by owenvoke**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| Fixed tickets | #...

### CODE REVIEW

**Comment by nunomaduro** [comment]
There is no more patch releases on phpunit 9.3.x series?

**Comment by owenvoke** [comment]
That's what I wasn't sure about. I was assuming there at least wouldn't be breaking changes to 9.3.x, but I guess there could be backports. Perhaps this should be `>= 9.3.7 <= 9.3.11 || 9.4.0` for now.

**Comment by nunomaduro** [comment]
> Perhaps this should be >= 9.3.7 <= 9.3.11 || 9.4.0 for now.

Yes, do it. Then you can merge and release.

**Comment by GrahamCampbell** [comment]
There will be no more 9.3.x releases of phpunit. I like the PR in it's current state.

**Comment by owenvoke** [comment]
Thanks for the clarification @GrahamCampbell, if that's ok with you @nunomaduro, shall I merge and release as is?

**Comment by nunomaduro** [comment]
Yes

**Pull request merged**
