### PR TITLE
Update globals.php

### PR DESCRIPTION
**Pull request by AlexMartinFR**
Typo.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| Fixed tickets | …

Just a typo.

### CODE REVIEW

**Comment by nunomaduro** [comment]
@owenvoke @AlexMartinFR You buddies can always merge pull requests once one person have accepted it.

**Comment by owenvoke** [comment]
Ah, forgot that I can. :+1: I'll keep that in mind for the future. :facepalm:

**Comment by AlexMartinFR** [comment]
I have read-only access on the Pest repo itself though 🙂

**Comment by nunomaduro** [comment]
@AlexMartinFR fixed

**Pull request merged**
