### PR TITLE
Add `throwsIf` exception

### PR DESCRIPTION
**Pull request by mertasan**
Moved: I submitted a new PR #371

### CODE REVIEW

**Review by owenvoke — COMMENTED** [review]
Maybe `throwsIf()` would be more consistent for the naming.

**Comment by mertasan** [comment]
@owenvoke you're right, I updated 👍

**Comment by nunomaduro** [comment]
I feel that `throwsWhen` reads better. What do you think?

**Review by owenvoke — COMMENTED** [review]
Would you mind running `composer update:snapshots` to update the snapshots?

This looks good to me otherwise though. 👍🏻

**Comment by mertasan** [comment]
Why does not work? What am I forgetting? @owenvoke 

https://user-images.githubusercontent.com/13007665/128540237-0ffa1579-8424-4e31-a2bc-90f135b55e09.mov

**Pull request closed without merging**
