### PR TITLE
[2.x] Junit support

### PR DESCRIPTION
**Pull request by nuernbergerA**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Fixed tickets | #774 #850 

Its mostly copy past from pests TeamCity implementation and phpunits JUnitLogger.

The only thing that im not able to fix is:
We write the xml file but it gets overwritten by phpunits xml file because i cant unregister their junit listener.

if i remove the following code from [`PHPUnit\TextUI\Application::class`](https://github.com/sebastianbergmann/phpunit/blob/b4d6098ec99bc802fd4916222678bb15cdec38d6/src/TextUI/Application.php#L551) it works
```php
if ($configuration->hasLogfileJunit()) {
    new JunitXmlLogger(
        OutputFacade::printerFor($configuration->logfileJunit()),
        EventFacade::instance(),
    );
}
```

maybe it would be better to overwrite the phpunit file where the try to figure out the filepath so we also fix the clover output

### CODE REVIEW

**Comment by nunomaduro** [comment]
@nuernbergerA Any plans to continue to work on this?

**Comment by nuernbergerA** [comment]
@nunomaduro sure if you tell me what's your favorite solution.

**Comment by nunomaduro** [comment]
What  phpunit file are we talking about?

**Comment by nuernbergerA** [comment]
https://github.com/sebastianbergmann/phpunit/blob/b4d6098ec99bc802fd4916222678bb15cdec38d6/src/TextUI/Application.php#L551

**Comment by nuernbergerA** [comment]
https://github.com/sebastianbergmann/phpunit/blob/main/src/Util/Reflection.php#L32C28-L32C45

or here
https://github.com/sebastianbergmann/phpunit/blob/3519f8063d9da6959c05bfd6b3002153babe0ffc/src/Event/Value/Test/TestMethodBuilder.php#L32

we could check if its an pest test and use pest suite and only fall back to reflection if its an "regular" phpunit test

**Comment by nunomaduro** [comment]
Go for the reflection one.

**Comment by nuernbergerA** [comment]
@nunomaduro I know you getting the line number of the failing tests from collision. Is there an API in v2 to get the line number (where the test is defined) in the original test file?

Also would it be ok for you if the `$_filename` would be a public const?

**Comment by nuernbergerA** [comment]
@nunomaduro the reflective approach was not enough, so i went with this

**Comment by michael-rubel** [comment]
@nuernbergerA @nunomaduro
Are there any plans to move this forward?

**Comment by nunomaduro** [comment]
Can you rebase this pull request, and remind me why we need this?

**Comment by nuernbergerA** [comment]
@nunomaduro ✅ rebased

This PR fixes two issues in junit:
- wrong test names ("it can set and get a name" vs "__pest_evaluable_it_can_set_and_get_a_name")
- wrong paths ("..../tests/DataTables/Columns/HasNameTest.php" vs "..../vendor/pestphp/pest/src/Factories/TestCaseFactory.php(196) : eval()'d code")

**Comment by nunomaduro** [comment]
But what's JUnit and why would we want to support it?

**Comment by nuernbergerA** [comment]
JUnit is an XML format for test results.
Its supported by phpunit see https://docs.phpunit.de/en/9.6/textui.html?highlight=JUnit#command-line-options

Bigger companies run CI/CD tools (most are more java orientated) like [jenkins](https://plugins.jenkins.io/junit/) and [sonarqube](https://www.sonarsource.com/products/sonarqube/) which both only work with JUnit

**Comment by calebdw** [comment]
> Bigger companies run CI/CD tools (most are more java orientated) like [jenkins](https://plugins.jenkins.io/junit/) and [sonarqube](https://www.sonarsource.com/products/sonarqube/) which both only work with JUnit

This is true, the only way to import my test report into Gitlab is with the JUnit format---these fixes would clean up the reporting!

**Comment by nuernbergerA** [comment]
@nunomaduro anything I can do to push this through the finish line?

**Comment by calebdw** [comment]
@nuernbergerA,

I'm not sure why, but after updating to the release containing these changes my pest tests are failing with:

```
In WorkerCrashedException.php line 41:
                                                                               
  The test "PARATEST='1' TEST_TOKEN='1' UNIQUE_TEST_TOKEN='1_65afff3fbe543' t  
  ests/Architecture/AbstractModelFactoryRuleTest.php" failed.                  
                                                                               
  Exit Code: 255(Unknown error)                                                
                                                                                                                                                              
  Output:                                                                      
  ================                                                             
                                                                               
     ERROR  Fatal error: Uncaught SebastianBergmann\CliParser\    
  RequiredOptionArgumentMissingException: Required argument for option "--log  
  -junit" is missing in /builds/web-developers/eaglesys/vendor/sebastian/cli-  
  parser/src/Parser.php:189
```

I'm running the tests with:

```bash
 vendor/bin/pest -p --processes=8 --log-junit pest.xml
```
note that I've tried both `--log-junit pest.xml` and `--log-junit=pest.xml` with the same failure.

Rolling Pest back to `v2.31.0` allows my tests to run again

**Comment by calebdw** [comment]
Actually the above error might be caused by @nunomaduro's changes: b9d2be87a28b218fd13d52df1c0d6c72d58cf191

**Pull request merged**
