### PR TITLE
[2.x] Print only files below the min coverage

### PR DESCRIPTION
**Pull request by WendellAdriel**
| Q             | A
| ------------- | ---
| Bug fix?      |no
| New feature?  | yes
| Fixed tickets |

This PR is adding a new `--errors-only` flag that when passed to the command call will print only the files that have coverage below the value set in with the `--min` argument

### CODE REVIEW

**Comment by WendellAdriel** [comment]
Hey @nunomaduro there are some failing checks but checking the details it doesn't seem related to my changes, let me know if I need to update anything here!

**Comment by devajmeireles** [comment]
@WendellAdriel , 

Thank you for your PR. Have you try to run the tests locally to check if happens the same error?

**Comment by WendellAdriel** [comment]
> @WendellAdriel ,
> 
> Thank you for your PR. Have you try to run the tests locally to check if happens the same error?

Yes and I don't get any errors on my local

**Comment by devajmeireles** [comment]
@WendellAdriel,

Could you sync your branch with the current `2.x` branch, please? This is the error:

CleanShot 2023-08-17 at 4 11 02

**Comment by WendellAdriel** [comment]
@devajmeireles I ran the wrong git command for sync and messed the branch
I'll create a new PR to organize this better

**Comment by WendellAdriel** [comment]
@devajmeireles the new PR is #919

**Pull request closed without merging**
