### PR TITLE
chore(composer): add support for PHPUnit 9.3.11

### PR DESCRIPTION
**Pull request by owenvoke**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| Fixed tickets | #... 

I've also updated to use a version selector, instead of a long list of all the patches that are supported.

### CODE REVIEW

**Comment by nunomaduro** [comment]
If tests are passing, this kind of stuff you can merge and tag. No need for approval.

**Comment by owenvoke** [comment]
I more just wanted to check that changing the version selector syntax was ok. Also got busy with work. 😬

**Comment by lcdss** [comment]
Why allowing phpunit ^9.0.0 would be a problem? I didn't understand the necessary to change the supported versions one by one.

**Comment by owenvoke** [comment]
@lcdss, it's because we use internal PHPUnit classes which aren't covered by the backwards compatibility guarantee. So they may be changed in a patch/minor version and Pest would break.

**Pull request merged**
