### PR TITLE
Fix junit parallel

### LINKED ISSUE #1070: [Bug]: Pest crashes when trying to output JUnit
### What Happened

Hello!

Please see related comment: https://github.com/pestphp/pest/pull/887#issuecomment-1906685934, creating an issue so thread doesn't get lost.

After updating to Pest v2.32.0 or higher my ci pipeline is failing with:

```
In WorkerCrashedException.php line 41:
                                                                               
  The test "PARATEST='1' TEST_TOKEN='1' UNIQUE_TEST_TOKEN='1_65afff3fbe543' t  
  ests/Architecture/AbstractModelFactoryRuleTest.php" failed.                  
                                                                               
  Exit Code: 255(Unknown error)                                                
                                                                                                                                                              
  Output:                                                                      
  ================                                                             
                                                                               
     ERROR  Fatal error: Uncaught SebastianBergmann\CliParser\    
  RequiredOptionArgumentMissingException: Required argument for option "--log  
  -junit" is missing in /builds/web-developers/eaglesys/vendor/sebastian/cli-  
  parser/src/Parser.php:189
```

I'm running the tests with:

```bash
 vendor/bin/pest -p --processes=8 --log-junit=pest.xml
```
note that I've tried both `--log-junit pest.xml` and `--log-junit=pest.xml` with the same failure.

Rolling Pest back to `v2.31.0` allows my tests to run again

Thanks!

### How to Reproduce

```bash
 vendor/bin/pest -p --processes=8 --log-junit=pest.xml
```

### Sample Repository

_No response_

### Pest Version

2.32.0

### PHP Version

8.2

### Operation System

Linux

### Notes

_No response_

### PR DESCRIPTION
**Pull request by nuernbergerA**
### What:
- [x] Bug Fix

### Description:
* revert JUnit Plugin so arguments can be used by paratest
* paratest makes direct calles to Junit logger (was overwritten by a noop class because we implement a own listener like we did for TeamCity) <- this was a bad idea
* copy pasted the latest original `JunitXmlLogger`
* injected the pest logging converter and replaced the small bits where we need to resolve pest names and filepaths
* changed the files as little as possible to keep future diffs as minimal as possible
* added comments on each line i modified to ensure its crystal clear what we changed

### Related:
Fixes #1070 
Caused by #887 and https://github.com/pestphp/pest/commit/b9d2be87a28b218fd13d52df1c0d6c72d58cf191

### How to test
```json
    "require-dev": {
        "pestphp/pest": "dev-fix-junit-parallel as v2.33"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/nuernbergerA/pest"
        }
    ],
```

### CODE REVIEW

**Comment by nuernbergerA** [comment]
@calebdw can you please test and confirm if this fixes all issues?

**Comment by calebdw** [comment]
I'm testing now

**Comment by calebdw** [comment]
I'm having trouble installing it:

```bash
$ composer update -W
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires pestphp/pest-plugin-faker ^2.0 -> satisfiable by pestphp/pest-plugin-faker[v2.0.0, 2.x-dev].
    - pestphp/pest-plugin-faker[v2.0.0, ..., 2.x-dev] require pestphp/pest ^2.0.0 -> found pestphp/pest[2.x-dev] but it conflicts with your root composer.json require (dev-
fix-junit-parallel).
  Problem 2
    - Root composer.json requires spatie/pest-plugin-test-time ^2.0 -> satisfiable by spatie/pest-plugin-test-time[2.0.0].
    - spatie/pest-plugin-test-time 2.0.0 requires pestphp/pest ^2.0 -> found pestphp/pest[2.x-dev] but it conflicts with your root composer.json require (dev-fix-junit-para
llel).
  Problem 3
    - pestphp/pest-plugin-laravel 2.x-dev requires pestphp/pest ^2.22.0 -> found pestphp/pest[2.x-dev] but it conflicts with your root composer.json require (dev-fix-junit-
parallel).
    - pestphp/pest-plugin-laravel v2.0.0 requires pestphp/pest ^2.0.0 -> found pestphp/pest[2.x-dev] but it conflicts with your root composer.json require (dev-fix-junit-pa
rallel).
    - pestphp/pest-plugin-laravel v2.1.0 requires pestphp/pest ^2.8.3 -> found pestphp/pest[2.x-dev] but it conflicts with your root composer.json require (dev-fix-junit-pa
rallel).
    - pestphp/pest-plugin-laravel v2.2.0 requires pestphp/pest ^2.13.0 -> found pestphp/pest[2.x-dev] but it conflicts with your root composer.json require (dev-fix-junit-p
arallel).
    - Root composer.json requires pestphp/pest-plugin-laravel ^2.0 -> satisfiable by pestphp/pest-plugin-laravel[v2.0.0, v2.1.0, v2.2.0, 2.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

**Comment by nuernbergerA** [comment]
@calebdw if updated the composer json

note the `as v2.33`  part to "trick" the plugins
```json
    "require-dev": {
        "pestphp/pest": "dev-fix-junit-parallel as v2.33"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/nuernbergerA/pest"
        }
    ],
```

**Comment by calebdw** [comment]
@nuernbergerA, everything seems to work great!

**Comment by nunomaduro** [comment]
@nuernbergerA After merging this pull request, the `--log-junit` works with parallel and non-parallel right?

**Comment by nuernbergerA** [comment]
@nunomaduro yes i double checked it and can confirm that it works with and without parallel.

**Pull request merged**
