### PR TITLE
Updated Functions::datasets() method by adding $scope parameter

### PR DESCRIPTION
**Pull request by DimionX**
### What:

- [ ] New Feature. Added the ability to use a custom scope for a datataset.

### Description:

Updated Functions::datasets() method signature by adding $scope optional parameter.

### CODE REVIEW

**Comment by fabio-ivona** [comment]
hi @DimionX could you elaborate more on the need behind this feature?

**Comment by DimionX** [comment]
> hi @DimionX could you elaborate more on the need behind this feature?

Since Dataset Boot connects tests from only one test directory, the limits their use in other scopes. For example, for component or unit tests that are located in the "app" directory, it is impossible to use a dataset that is located in the test directory (tests).
Thus, you can manually specify which scope a particular dataset belongs to.

**Comment by fabio-ivona** [comment]
@DimionX I see, would you mind to add some test for your changes?

**Comment by nunomaduro** [comment]
Just place those "global" datasets on the "tests/Datasets" folder.

**Pull request closed without merging**
